"""Working around the noise channel's lack of `@ve` support (see
mml2wla_documentation.md's Noise channel and Volume envelopes sections):
the target engine bakes a fixed envelope pace into each noise-table entry,
so `@ve` on the noise channel has nothing to attach to and is dropped by
the main converter.

This module implements two independent ways to recover the intended
envelope, operating on a fully-parsed channel D event stream:

- `compute_new_table_entries`: for every distinct (frequency, envelope)
  combination the noise channel actually asks for, propose a brand new
  noise-table row with an *exact* match for both (not a nearest-match
  against the fixed palette) -- analogous to how waveforms.py proposes new
  waveform-table entries. This is the more faithful fix, but requires
  merging new rows into the target project's noise table.

- `expand_with_retrigger`: simulates the real hardware envelope per note
  (mmlgb writes `NRx2 = volume | envelope` directly to hardware -- see
  envelope.py's module docstring for the full derivation) and "samples" the
  resulting volume curve by retriggering the note at each envelope step
  with an explicit `v` write, using only already-supported commands. This
  needs no changes to the target project's noise table, at the cost of a
  much more verbose (and slightly less faithful, since retriggering restarts
  the noise LFSR phase each step) channel D.
"""

from dataclasses import dataclass
from typing import Dict, List, Optional, Tuple

from .lexer import Token, MmlError
from .parser import Ev, RepeatBlock, Parser, TokenStream, structure
from .timing import real_seconds_per_tick, chunk_length
from .notes import NOTE_NAMES
from .noise import mmlgb_noise_exact_nr43, REFERENCE_NOISE_ENTRIES

GB_ENVELOPE_HZ = 64.0
DEFAULT_VOLUME = 15


def _direction_of(ve_signed: int) -> Optional[str]:
    if ve_signed > 0:
        return 'inc'
    if ve_signed < 0:
        return 'dec'
    return None


# ---------------------------------------------------------------------------
# Default mode: propose new noise-table entries
# ---------------------------------------------------------------------------

@dataclass
class NewNoiseEntry:
    nr43: int
    env_byte: int
    octave: int
    note_idx: int
    pace: int
    direction: str
    line: int


def _walk_flat(nodes: list):
    """Yields Ev leaves in order, treating repeat blocks as visited once
    (sufficient for the *set* of distinct combinations used -- repeating a
    block doesn't introduce any new combination, just reuses one)."""
    for node in nodes:
        if isinstance(node, RepeatBlock):
            yield from _walk_flat(node.children)
        else:
            yield node


def compute_new_table_entries(events: List[Ev]) -> List[NewNoiseEntry]:
    tree = structure(events)
    existing_pairs = {(env & 0x0F, nr43) for (_note, env, nr43) in REFERENCE_NOISE_ENTRIES}

    cur_pace, cur_dir = 0, None
    seen: Dict[Tuple[int, int], NewNoiseEntry] = {}
    order: List[Tuple[int, int]] = []

    for ev in _walk_flat(tree):
        if ev.kind == 'env':
            cur_pace, cur_dir = abs(ev.a), _direction_of(ev.a)
        elif ev.kind == 'note':
            if cur_pace <= 0 or cur_dir is None:
                continue
            note_idx, octave = ev.a, ev.b
            nr43 = mmlgb_noise_exact_nr43(octave, note_idx)
            env_byte = cur_pace | (0x08 if cur_dir == 'inc' else 0)
            key = (env_byte, nr43)
            if key in existing_pairs:
                continue
            if key not in seen:
                seen[key] = NewNoiseEntry(nr43, env_byte, octave, note_idx,
                                           cur_pace, cur_dir, ev.line)
                order.append(key)

    return [seen[k] for k in order]


def format_table_entries(entries: List[NewNoiseEntry], start_note_byte: int = 0x60) -> str:
    if not entries:
        return ""
    used_bytes = {note for note, _env, _nr43 in REFERENCE_NOISE_ENTRIES}
    lines = []
    lines.append("; Auto-generated by noise_envelope.py. These are new noise-table entries")
    lines.append("; needed to give the source song exact per-note envelope control on the")
    lines.append("; noise channel, which the fixed palette in your project's noise table")
    lines.append("; (e.g. audio/common/noise.s) can't already provide -- this engine bakes")
    lines.append("; envelope pace directly into which fixed noise type gets picked, so getting")
    lines.append("; the envelope right requires a table entry with that exact combination of")
    lines.append("; frequency AND envelope pace/direction already baked in. See")
    lines.append("; mml2wla_documentation.md's \"Volume envelopes\" and \"Noise channel\" sections.")
    lines.append(";")
    lines.append("; Merge the rows below into your project's noise table, before its")
    lines.append("; terminating `.db $ff` sentinel row. The placeholder note-byte values (b0,")
    lines.append(f"; the lookup key) start at ${start_note_byte:02x} to avoid colliding with the reference")
    lines.append("; table's existing entries -- verify against your project's current table and")
    lines.append("; renumber if needed. Row format matches the reference table exactly:")
    lines.append(";   b0: note byte (arbitrary, must be unique in the table)")
    lines.append(";   b1: envelope byte (bit3: 0=decreasing/1=increasing; bits2-0: pace 0-7)")
    lines.append(";   b2: NR43 byte (exact frequency match for the source pitch)")
    lines.append(";")
    lines.append("; After merging, also add matching entries to REFERENCE_NOISE_ENTRIES in")
    lines.append("; src/mml2wla/noise.py so future mml2wla conversions of this song (or any other")
    lines.append("; using the same noise pitch/envelope combination) pick these up automatically")
    lines.append("; via the normal nearest-match lookup, instead of only an approximate match.")
    lines.append("")

    note_byte = start_note_byte
    for entry in entries:
        while note_byte in used_bytes:
            note_byte += 1
        name = f"{NOTE_NAMES[entry.note_idx]}{entry.octave}"
        dir_word = "increasing" if entry.direction == 'inc' else "decreasing"
        lines.append(f"; source: o{entry.octave} {name} with envelope pace {entry.pace} ({dir_word}), line {entry.line}")
        lines.append(f"\t.db ${note_byte:02x} ${entry.env_byte:02x} ${entry.nr43:02x}")
        used_bytes.add(note_byte)
        note_byte += 1
    return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# Live aggregator used by mml2wla.py itself (the --noise-envelope flag): the
# same "propose an exact new entry" logic as compute_new_table_entries above,
# but called incrementally during normal conversion so the generated song
# can reference the new entries directly, deduplicated across a whole
# --batch run the same way waveforms.WaveformAggregator dedupes waveform
# variants.
# ---------------------------------------------------------------------------

class NoiseEnvelopeAggregator:
    def __init__(self, start_note_byte: int = 0x60):
        self.entries = []  # [{nr43, env_byte, note_byte, users:set(...)}]
        self.by_key: Dict[Tuple[int, int], int] = {}
        self.used_bytes = {note for note, _env, _nr43 in REFERENCE_NOISE_ENTRIES}
        self._next_byte = start_note_byte

    def request(self, octave: int, note_idx: int, pace: int, direction: str,
                song_name: str, line: int) -> int:
        """Returns the note byte to use for a noise note at (octave,
        note_idx) with an active envelope (pace, direction), creating a new
        table entry if this exact combination hasn't been requested yet."""
        nr43 = mmlgb_noise_exact_nr43(octave, note_idx)
        env_byte = pace | (0x08 if direction == 'inc' else 0)
        key = (env_byte, nr43)
        if key in self.by_key:
            idx = self.by_key[key]
            self.entries[idx]['users'].add((song_name, octave, note_idx, line))
            return self.entries[idx]['note_byte']

        while self._next_byte in self.used_bytes:
            self._next_byte += 1
        note_byte = self._next_byte
        self.used_bytes.add(note_byte)
        self._next_byte += 1

        idx = len(self.entries)
        self.entries.append({
            'nr43': nr43,
            'env_byte': env_byte,
            'note_byte': note_byte,
            'pace': pace,
            'direction': direction,
            'users': {(song_name, octave, note_idx, line)},
        })
        self.by_key[key] = idx
        return note_byte

    def emit(self) -> str:
        if not self.entries:
            return ""
        lines = []
        lines.append("; Auto-generated by mml2wla.py (--noise-envelope). These are new")
        lines.append("; noise-table entries needed to give the converted song(s) below exact")
        lines.append("; per-note envelope control on the noise channel, which the fixed palette")
        lines.append("; in your project's noise table (e.g. audio/common/noise.s) doesn't already")
        lines.append("; provide -- this engine bakes envelope pace directly into which fixed")
        lines.append("; noise type gets picked, so getting the envelope right requires a table")
        lines.append("; entry with that exact combination of frequency AND envelope pace/")
        lines.append("; direction already baked in. See mml2wla_documentation.md's \"Volume")
        lines.append("; envelopes\" and \"Noise channel\" sections.")
        lines.append(";")
        lines.append("; The converted song(s) already reference these entries by the note byte")
        lines.append("; values below (b0) -- merge the rows into your project's noise table,")
        lines.append("; before its terminating `.db $ff` sentinel row, using those exact byte")
        lines.append("; values (don't renumber b0 without also updating the generated .s files).")
        lines.append("; Row format matches the reference table exactly:")
        lines.append(";   b0: note byte (lookup key, matches `note $XX ...` in the generated .s)")
        lines.append(";   b1: envelope byte (bit3: 0=decreasing/1=increasing; bits2-0: pace 0-7)")
        lines.append(";   b2: NR43 byte (exact frequency match for the source pitch)")
        lines.append("")
        for entry in self.entries:
            users = sorted(entry['users'])
            lines.append("; Used by:")
            for song_name, octave, note_idx, line in users:
                name = f"{NOTE_NAMES[note_idx]}{octave}"
                lines.append(f";   {song_name}.s (source o{octave} {name}, line {line})")
            lines.append(f"\t.db ${entry['note_byte']:02x} ${entry['env_byte']:02x} ${entry['nr43']:02x}")
            lines.append("")
        return '\n'.join(lines) + '\n'


# ---------------------------------------------------------------------------
# --expand mode: retrigger simulation
# ---------------------------------------------------------------------------

def _env_steps(total_ticks: int, bpm: float, pace: int, direction: Optional[str],
               start_vol: int) -> List[Tuple[int, int]]:
    """Returns [(vol, ticks), ...] segments approximating the real hardware
    envelope curve for a note/hold of `total_ticks`, by retriggering with an
    explicit volume at each real envelope step boundary."""
    if pace <= 0 or direction is None:
        return [(start_vol, total_ticks)]

    step_ticks_exact = (pace / GB_ENVELOPE_HZ) / real_seconds_per_tick(bpm)
    segments: List[Tuple[int, int]] = []
    vol = start_vol
    remaining = total_ticks
    carry = 0.0

    while remaining > 0:
        at_limit = (direction == 'inc' and vol >= 15) or (direction == 'dec' and vol <= 0)
        if at_limit:
            segments.append((vol, remaining))
            break
        total = step_ticks_exact + carry
        seg = max(1, round(total))
        if seg >= remaining:
            segments.append((vol, remaining))
            break
        segments.append((vol, seg))
        carry = total - seg
        remaining -= seg
        vol = min(15, vol + 1) if direction == 'inc' else max(0, vol - 1)

    return segments


class _OpenNote:
    __slots__ = ('note_idx', 'octave', 'vol', 'pace', 'direction', 'carry')

    def __init__(self, note_idx, octave, vol, pace, direction):
        self.note_idx = note_idx
        self.octave = octave
        self.vol = vol
        self.pace = pace
        self.direction = direction
        self.carry = 0.0

    def step(self, total_ticks: int, bpm: float) -> List[Tuple[int, int]]:
        """Consumes `total_ticks` starting from this note's current position
        in its envelope curve (continuing, not resetting -- for standalone
        ties/waits that extend an already-sounding note)."""
        if self.pace <= 0 or self.direction is None:
            return [(self.vol, total_ticks)]
        step_ticks_exact = (self.pace / GB_ENVELOPE_HZ) / real_seconds_per_tick(bpm)
        segments = []
        remaining = total_ticks
        while remaining > 0:
            at_limit = (self.direction == 'inc' and self.vol >= 15) or \
                       (self.direction == 'dec' and self.vol <= 0)
            if at_limit:
                segments.append((self.vol, remaining))
                break
            total = step_ticks_exact + self.carry
            seg = max(1, round(total))
            if seg >= remaining:
                segments.append((self.vol, remaining))
                break
            segments.append((self.vol, seg))
            self.carry = total - seg
            remaining -= seg
            self.vol = min(15, self.vol + 1) if self.direction == 'inc' else max(0, self.vol - 1)
        return segments


def expand_with_retrigger(events: List[Ev]) -> List[Ev]:
    """Flattens (fully unrolling repeats) and rewrites channel D's event
    stream, replacing every envelope-affected note/hold with explicit
    volume writes + retriggers, so the result no longer needs `@ve`/`env`
    at all on this channel."""
    tree = structure(events)
    out: List[Ev] = []
    cur_vol = DEFAULT_VOLUME
    cur_pace, cur_dir = 0, None
    open_note: Optional[_OpenNote] = None

    def emit_segments(note_idx, octave, segments, line):
        for vol, ticks in segments:
            out.append(Ev('vol', line, vol))
            for chunk in chunk_length_mml(ticks):
                out.append(Ev('note', line, note_idx, octave, chunk, None))

    def walk(nodes):
        nonlocal cur_vol, cur_pace, cur_dir, open_note
        for node in nodes:
            if isinstance(node, RepeatBlock):
                for _ in range(node.count):
                    walk(node.children)
                continue
            ev = node
            if ev.kind == 'vol':
                cur_vol = ev.a
                if open_note is not None:
                    open_note.vol = cur_vol
                out.append(Ev('vol', ev.line, cur_vol))
            elif ev.kind == 'env':
                cur_pace, cur_dir = abs(ev.a), _direction_of(ev.a)
            elif ev.kind == 'note':
                note_idx, octave, ticks, bpm = ev.a, ev.b, ev.c, ev.d
                if cur_pace > 0 and cur_dir is not None:
                    open_note = _OpenNote(note_idx, octave, cur_vol, cur_pace, cur_dir)
                    segments = open_note.step(ticks, bpm)
                    emit_segments(note_idx, octave, segments, ev.line)
                else:
                    open_note = None
                    out.append(Ev('vol', ev.line, cur_vol))
                    for chunk in chunk_length_mml(ticks):
                        out.append(Ev('note', ev.line, note_idx, octave, chunk, None))
            elif ev.kind == 'wait':
                ticks, bpm = ev.a, ev.b
                if open_note is not None:
                    segments = open_note.step(ticks, bpm)
                    emit_segments(open_note.note_idx, open_note.octave, segments, ev.line)
                else:
                    out.append(ev)
            elif ev.kind == 'rest':
                open_note = None
                out.append(ev)
            elif ev.kind == 'loop':
                out.append(ev)
            elif ev.kind == 'tempo':
                # Passed through unchanged: this only reorders/rewrites
                # channel D's own note/envelope events, and D always saw
                # its own `t` commands in correct chronological order
                # already (they're declared on D itself) -- the cross-
                # channel tempo bug tempo.py fixes is specifically about
                # *other* channels not seeing D's tempo changes, which
                # doesn't apply within this single-channel rewrite.
                out.append(ev)
            elif ev.kind == 'comment':
                # Dropped, not reproduced: the surrounding text-surgery
                # (rewrite_with_expanded_noise) already preserves every
                # comment at its original position untouched. Since a
                # comment on its own line gets attached to channel D's
                # event stream whenever D is the *next* channel line
                # (matching the main converter's behavior), reproducing it
                # here too would duplicate it -- once at its original
                # position, once in the regenerated D block.
                pass
            else:
                raise ValueError(f"internal: unhandled event kind {ev.kind!r}")

    walk(tree)
    return _dedup_consecutive_vol(out)


def _dedup_consecutive_vol(events: List[Ev]) -> List[Ev]:
    """Drops a `vol` event that's immediately followed by another `vol`
    event of the same value (e.g. an explicit `v10` in the source directly
    followed by an envelope-triggered note whose first segment is also
    volume 10) -- cosmetic only, doesn't change the resulting sound."""
    out: List[Ev] = []
    for i, ev in enumerate(events):
        if ev.kind == 'vol' and i + 1 < len(events) and \
                events[i + 1].kind == 'vol' and events[i + 1].a == ev.a:
            continue
        out.append(ev)
    return out


def chunk_length_mml(total_ticks: int) -> List[int]:
    """MML's `=N` explicit-length form is capped at 255 (see the mmlgb
    grammar) -- split anything longer into multiple same-volume segments."""
    if total_ticks <= 0:
        return []
    chunks = []
    remaining = total_ticks
    while remaining > 255:
        chunks.append(255)
        remaining -= 255
    if remaining > 0:
        chunks.append(remaining)
    return chunks


# ---------------------------------------------------------------------------
# MML serialization for the expanded channel D stream
# ---------------------------------------------------------------------------

def _note_token(note_idx: int) -> str:
    """MML has no two-letter note tokens -- a sharp is the base letter plus
    a separate `+` modifier, e.g. index 1 (NOTE_NAMES[1] == "cs") is written
    `c+`, not `cs`."""
    name = NOTE_NAMES[note_idx]
    return name[0] + '+' if name.endswith('s') else name


def serialize_channel_d(events: List[Ev]) -> List[str]:
    """Renders an expanded channel D event stream (from expand_with_retrigger)
    back into MML source lines, prefixed with `D `."""
    lines = []
    cur_octave = None
    tokens: List[str] = []

    def flush():
        nonlocal tokens
        if tokens:
            lines.append('D ' + ' '.join(tokens))
            tokens = []

    for ev in events:
        if ev.kind == 'comment':
            flush()
            lines.append(ev.a)
            continue
        if ev.kind == 'loop':
            tokens.append('L')
            continue
        if ev.kind == 'tempo':
            tokens.append(f"t{ev.a}")
            continue
        if ev.kind == 'rest':
            tokens.extend(f"r={c}" for c in chunk_length_mml(ev.a))
        elif ev.kind == 'wait':
            tokens.extend(f"^={c}" for c in chunk_length_mml(ev.a))
        elif ev.kind == 'vol':
            tokens.append(f"v{ev.a}")
        elif ev.kind == 'note':
            note_idx, octave, ticks = ev.a, ev.b, ev.c
            if octave != cur_octave:
                tokens.append(f"o{octave}")
                cur_octave = octave
            tokens.append(f"{_note_token(note_idx)}={ticks}")
        else:
            raise ValueError(f"internal: unexpected kind {ev.kind!r} in expanded channel D stream")

        if len(tokens) >= 24:
            flush()

    flush()
    return lines


# ---------------------------------------------------------------------------
# --expand mode: text surgery (only channel D's lines are touched; every
# other line -- including channels A/B/C, their comments, and any @@ macros
# they rely on -- is left byte-for-byte untouched)
# ---------------------------------------------------------------------------

def scan_channel_d_lines(tokens: List[Token]) -> Tuple[List[int], List[int]]:
    """Returns (d_only_lines, mixed_lines): source line numbers of
    statements that select channel D alone, and ones that combine D with
    another channel on the same line (not supported -- MML has no way to
    give different channels on a shared line different replacement text)."""
    ts = TokenStream(tokens)
    d_lines: List[int] = []
    mixed_lines: List[int] = []
    while ts.cur.type != 'EOF':
        if ts.cur.type == 'CHANNEL':
            line = ts.cur.line
            letters = []
            while ts.cur.type == 'CHANNEL':
                letters.append(ts.eat().data)
            while ts.cur.type not in ('NEWLINE', 'EOF'):
                ts.eat()
            if ts.cur.type == 'NEWLINE':
                ts.eat()
            if 'D' in letters:
                (mixed_lines if len(letters) > 1 else d_lines).append(line)
        elif ts.cur.type == 'MACRO' and ts.cur.data in ('@wave', '@@'):
            # Skip the whole definition block without needing to fully
            # parse it -- it can't contain a top-level channel line.
            while ts.cur.type not in ('RCURLY', 'EOF'):
                ts.eat()
            if ts.cur.type == 'RCURLY':
                ts.eat()
            if ts.cur.type == 'NEWLINE':
                ts.eat()
        else:
            ts.eat()
    return d_lines, mixed_lines


def rewrite_with_expanded_noise(mml_text: str) -> str:
    """Returns a full copy of `mml_text` with channel D's lines replaced by
    an envelope-expanded rewrite (see expand_with_retrigger), and every
    other line left completely untouched."""
    from .lexer import lex

    tokens = lex(mml_text)
    d_lines, mixed_lines = scan_channel_d_lines(tokens)
    if mixed_lines:
        where = ', '.join(str(l) for l in sorted(mixed_lines))
        raise MmlError(
            f"channel D is combined with another channel on line(s) {where}; "
            f"put channel D on its own dedicated line(s) before running this script "
            f"(MML has no way to give one channel different replacement text than "
            f"another on a shared line).")
    if not d_lines:
        raise MmlError("no noise channel (D) content found in this file")

    parser = Parser(tokens)
    song = parser.parse()
    expanded = expand_with_retrigger(song.channels[3])
    new_lines = serialize_channel_d(expanded)

    src_lines = mml_text.split('\n')
    d_line_set = set(d_lines)
    first_d_line = min(d_lines)
    out_lines = []
    for i, line in enumerate(src_lines, start=1):
        if i in d_line_set:
            if i == first_d_line:
                out_lines.extend(new_lines)
            continue  # other D lines: dropped, merged into the first D position
        out_lines.append(line)
    trailing_newline = '\n' if mml_text.endswith('\n') else ''
    return '\n'.join(out_lines) + trailing_newline
