; This table defines the types of noises the noise channel can make.
;
; Data format:
;   b0: "Note", aka the value passed to the "note" macro, used as a lookup index for this table
;   b1: Controls volume envelope, NR42 register (should always leave upper nybble as $0)
;   b2: Value written directly to NR43 register (determines most characteristics of the sound)

noiseFrequencyTable:
	.db $24 $01 $47
	.db $22 $00 $47
	.db $23 $02 $46
	.db $26 $02 $26
	.db $28 $00 $35
	.db $27 $02 $14
	.db $2a $01 $14
	.db $2e $06 $07
	.db $52 $03 $17
	.db $32 $02 $37
	.db $2f $02 $45
	.db $29 $02 $47
	.db $30 $00 $07

.ifndef BUILD_VANILLA
	; Increasing-envelope (fade-in) variants: same NR43 characteristics as an existing
	; entry above, but with the envelope byte's bit 3 set (direction = increase instead
	; of decrease). More of these can be appended here (by hand, or generated by
	; mml2wla's noise_envelope.py, which already knows how to synthesize exact new
	; entries) as songs need other noise timbres with a fade-in. Guarded out of the
	; vanilla build since bank $39 has no free space there and vanilla data never
	; references these note bytes.
	.db $25 $09 $47 ; fade-in variant of $22 (crash)
	.db $2c $09 $47 ; fade-in variant of $24 (snare)
	.db $2b $0a $37 ; fade-in variant of $32 (dash noise)
.endif

	.db $ff
