#!/usr/bin/python3
"""Generates audio/common/noise.s from audio/common/noise.json -- the noise
channel's fixed hardware "note" palette is now authored as JSON (note byte,
envelope byte, NR43 byte, and an optional name/description for whichever
entries get a real MML alias -- see sToMml.py's use of these same names for
`@alias = n$XX` definitions), with this script doing the table-generation
work that used to be done by hand in the committed .s file.

An entry with "editableOnly": true (the hardware envelope fade-in variants
-- see code/audio.s's engine support for the increasing-envelope direction
bit) is emitted inside a `.ifndef BUILD_VANILLA` guard, exactly matching
the original hand-written noise.s: real entries the noise channel can
select once compiled through the editable build, but never present in
vanilla ROM data (bank $39 has no free space there for them).

Usage: noiseJsonToS.py <noise.json> <noise.s>
"""
import json
import sys


def generate(entries):
    out = []
    out.append("; Generated by tools/audio/noiseJsonToS.py from noise.json -- do not edit "
               "directly.")
    out.append(";")
    out.append("; This table defines the types of noises the noise channel can make.")
    out.append(";")
    out.append("; Data format:")
    out.append(";   b0: \"Note\", aka the value passed to the \"note\" macro, used as a lookup "
               "index for this table")
    out.append(";   b1: Controls volume envelope, NR42 register (should always leave upper "
               "nybble as $0)")
    out.append(";   b2: Value written directly to NR43 register (determines most "
               "characteristics of the sound)")
    out.append("")
    out.append("noiseFrequencyTable:")

    def emit_row(e):
        comment = e.get('description') or e.get('comment')
        name = e.get('name')
        label = f" ; {name}: {comment}" if name and comment else (
            f" ; {comment}" if comment else (f" ; {name}" if name else ""))
        out.append(f"\t.db ${e['note']:02x} ${e['env']:02x} ${e['nr43']:02x}{label}")

    vanilla = [e for e in entries if not e.get('editableOnly')]
    editable_only = [e for e in entries if e.get('editableOnly')]
    for e in vanilla:
        emit_row(e)

    if editable_only:
        out.append("")
        out.append(".ifndef BUILD_VANILLA")
        out.append("\t; Increasing-envelope (fade-in) variants: same NR43 characteristics as an "
                   "existing")
        out.append("\t; entry above, but with the envelope byte's bit 3 set (direction = "
                   "increase instead")
        out.append("\t; of decrease). Guarded out of the vanilla build since bank $39 has no "
                   "free space")
        out.append("\t; there and vanilla data never references these note bytes.")
        for e in editable_only:
            emit_row(e)
        out.append(".endif")

    out.append("")
    out.append("\t.db $ff")
    out.append("")
    return '\n'.join(out)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <noise.json> <noise.s>")
        sys.exit(1)
    json_path, out_path = sys.argv[1], sys.argv[2]
    with open(json_path) as f:
        entries = json.load(f)
    text = generate(entries)
    with open(out_path, 'w') as f:
        f.write(text)
    print(f"wrote {out_path} ({len(entries)} noise entr{'y' if len(entries)==1 else 'ies'})")


if __name__ == '__main__':
    main()
