#!/usr/bin/python3
"""Generates audio/common/waveforms.s from audio/common/waveforms.json --
the wave channel's waveform table is now authored as JSON (id, name, and 32
space-separated 0-15 samples -- the same unpacked-nibble format a .mml
file's own `@waveN = {...}` uses, see mml2wla/parser.py), with this script
doing the packing (2 samples/byte, high nibble first) and table-generation
work that used to be done by hand in the committed .s file.

Ids must be exactly 0..N-1 with no gaps -- they're used directly as the
wave channel's `duty $XX` value, so the generated waveformTable has to be
dense. Run tools/audio/dumpMusicMml.py/dumpSfxMml.py first if you want to
add or renumber an entry that existing .mml songs already reference by
name; this script only ever regenerates waveforms.s from whatever
waveforms.json currently says.

The 8 anonymous, never-referenced "Unused" data blocks in the original
vanilla waveforms.s (dead bytes physically present in the real cartridge
between named entries, confirmed by the fact that every real index 0-45 is
*already* densely covered by named entries alone -- see the exploration
that found this) aren't part of waveforms.json at all: they carry no name,
no id, and aren't reachable via any `duty` value, so there's nothing for a
song to author. They're reproduced here verbatim, appended after the real
table and gated to BUILD_VANILLA only, purely so a from-scratch vanilla
build still has the same total ROM byte count in this bank as the real
cartridge -- editable builds don't carry this dead weight at all, a small,
genuine ROM-space win in line with this whole migration's goal.

Usage: waveformsJsonToS.py <waveforms.json> <waveforms.s>
"""
import json
import sys

# Verbatim from the original vanilla waveforms.s (see the exploration that
# confirmed these 8 blocks are unreferenced by any `duty` value or the
# waveformTable's own dense 0-45 index range) -- vanilla-only ROM-space
# filler, not real editable-build content. See this module's docstring.
_VANILLA_UNUSED_BLOCKS = [
    "00 00 00 00 66 77 88 88 88 88 88 88 88 77 66 55",
    "00 00 00 00 88 88 88 88 88 88 88 88 88 88 88 88",
    "ff ee cc bb 99 88 66 55 cc aa 99 77 66 44 22 00",
    "88 aa cc ee ff ee dd cc bb aa 99 88 66 44 22 00",
    "ff f6 db ae 80 4f 25 0a 00 0a 25 4f 80 ae db f6",
    "c0 db c0 80 40 25 40 80 c0 db c0 80 40 25 40 80",
    "20 37 40 37 20 0a 00 0a 20 37 40 37 20 0a 00 0a",
    "01 23 45 67 89 ab cd ef fe dc ba 98 76 54 32 10",
]


def pack(samples):
    """32 4-bit samples -> 16 bytes, high nibble first -- see
    mml2wla/waveforms.py's pack_wave_samples for the same packing, verified
    there against a hand-authored reference waveform's actual shape."""
    out = []
    for i in range(0, 32, 2):
        out.append(((samples[i] & 0xf) << 4) | (samples[i + 1] & 0xf))
    return out


def generate(entries):
    entries = sorted(entries, key=lambda e: e['id'])
    expected_ids = list(range(len(entries)))
    actual_ids = [e['id'] for e in entries]
    if actual_ids != expected_ids:
        raise ValueError(
            f"waveforms.json ids must be exactly 0..{len(entries) - 1} with no gaps or "
            f"duplicates (got {actual_ids}) -- the wave channel's `duty $XX` dispatch needs "
            f"a dense table.")

    out = []
    out.append("; Generated by tools/audio/waveformsJsonToS.py from waveforms.json -- do not "
               "edit directly.")
    out.append(";")
    out.append("; These are the waveforms available on the wave channel. Using the command "
               "\"duty $XX\" will")
    out.append("; use waveform number XX in this table.")
    out.append("")
    out.append(f".define NUM_WAVEFORMS ${len(entries):02x}")
    out.append("")
    out.append("; Table of pointers to waveform data")
    out.append("waveformTable:")
    out.append("\t.rept NUM_WAVEFORMS index i")
    out.append("\t\t.dw @waveform{%.2x{i}}")
    out.append("\t.endr")
    out.append("")
    out.append("")
    for entry in entries:
        samples = [int(s) for s in entry['data'].split()]
        if len(samples) != 32:
            raise ValueError(f"waveform id {entry['id']} ({entry['name']}): expected 32 "
                              f"samples, got {len(samples)}")
        for s in samples:
            if s < 0 or s > 15:
                raise ValueError(f"waveform id {entry['id']} ({entry['name']}): sample {s} "
                                  f"out of range 0-15")
        packed = pack(samples)
        out.append(f"m_waveform ${entry['id']:02x}, {entry['name']}")
        out.append("\t.db " + ' '.join(f"${b:02x}" for b in packed))
        out.append("")

    out.append(".ifdef BUILD_VANILLA")
    out.append("\t; Dead, unreferenced filler bytes -- see this script's own docstring for why "
               "these are")
    out.append("\t; reproduced here instead of in waveforms.json.")
    for block in _VANILLA_UNUSED_BLOCKS:
        out.append("\t.db " + ' '.join(f"${b}" for b in block.split()))
    out.append(".endif")
    out.append("")
    return '\n'.join(out)


def main():
    if len(sys.argv) != 3:
        print(f"Usage: {sys.argv[0]} <waveforms.json> <waveforms.s>")
        sys.exit(1)
    json_path, out_path = sys.argv[1], sys.argv[2]
    with open(json_path) as f:
        entries = json.load(f)
    text = generate(entries)
    with open(out_path, 'w') as f:
        f.write(text)
    print(f"wrote {out_path} ({len(entries)} waveform(s))")


if __name__ == '__main__':
    main()
