"""Wave channel (channel C) sample scaling, packing, and cross-file dedup.

Real Game Boy wave-channel hardware only supports four output levels: mute,
100%, 50%, 25% (NR32 bits 6-5, applied as a 0/1/2-bit right shift of each
4-bit sample as it's read from Wave RAM). mmlgb exposes this directly as
`v0`-`v3`, changeable per note.

The target WLA sound engine's `vol` command is wired to do nothing on the
wave channel -- volume has to be baked into the waveform sample data itself
(this is confirmed both by s_file_documentation.mediawikipage and by the
reference engine's own code, which skips the wave channel in `cmdVolume`).
The reference waveforms.s does exactly this by hand, with families like
`WF_SQUARE_50_VOL_1`..`VOL_9` at different hand-picked amplitudes.

So: for every (waveform, volume level) pair actually used by a song's wave
channel, we generate a scaled variant of that waveform's 32 samples using
the same shift amounts real hardware would apply, and let the channel data
select between them with `duty`. Variants are deduplicated by their final
packed byte content, so identical (waveform, volume) pairs -- even across
different songs in a batch run -- share one table entry.
"""

from typing import Dict, List, Tuple

WAVE_VOLUME_SHIFT = {0: None, 1: 2, 2: 1, 3: 0}  # None = fully muted
VOL_LABEL = {0: 'MUTE', 1: '25', 2: '50', 3: '100'}


def scale_wave_samples(samples: List[int], vol_level: int) -> List[int]:
    shift = WAVE_VOLUME_SHIFT[vol_level]
    if shift is None:
        return [0] * 32
    return [s >> shift for s in samples]


def pack_wave_samples(samples: List[int]) -> List[int]:
    """32 4-bit samples -> 16 bytes, high nibble first. Verified against
    both mmlgb's own Song.EmitC() packing (parser/src/Song.cs) and the
    reference waveforms.s: a hand-authored triangle wave (WF_TRIANGLE_MEDIUM,
    `.db $11 $22 $33 $44 $55 $66 $78 $9a $a9 $88 ...`) only unpacks into a
    smooth, monotonic ramp with this nibble order; the reverse order breaks
    the ramp into a small zigzag at the peak, which would be an implausible
    shape for a hand-authored "triangle" waveform."""
    out = []
    for i in range(0, 32, 2):
        out.append(((samples[i] & 0xF) << 4) | (samples[i + 1] & 0xF))
    return out


class WaveformAggregator:
    """Collects scaled waveform variants across one or more converted
    songs, deduplicated by exact packed byte content, with usage tracked
    per (song, source wave id, volume level) for the generated comments."""

    def __init__(self, next_free_id_hint: int = 0x2e):
        self.entries = []  # [{packed, name, users:set((song,waveid,vol))}]
        self.by_bytes: Dict[tuple, int] = {}
        self.by_name: set = set()
        self.next_free_id_hint = next_free_id_hint

    def request(self, raw_samples: List[int], vol_level: int, song_name: str, base_wave_id: int) -> str:
        scaled = scale_wave_samples(raw_samples, vol_level)
        packed = tuple(pack_wave_samples(scaled))
        if packed in self.by_bytes:
            idx = self.by_bytes[packed]
            self.entries[idx]['users'].add((song_name, base_wave_id, vol_level))
            return self.entries[idx]['name']

        base_name = f"WF_{song_name.upper()}_WAVE{base_wave_id}_{VOL_LABEL[vol_level]}"
        name = base_name
        suffix = 1
        while name in self.by_name:
            suffix += 1
            name = f"{base_name}_{suffix}"
        self.by_name.add(name)

        idx = len(self.entries)
        self.entries.append({
            'packed': packed,
            'name': name,
            'users': {(song_name, base_wave_id, vol_level)},
        })
        self.by_bytes[packed] = idx
        return name

    def emit(self) -> str:
        if not self.entries:
            return ""
        lines = []
        lines.append("; Auto-generated by mml2wla. These waveforms are new and are NOT yet")
        lines.append("; part of your project's waveform table (e.g. audio/common/waveforms.s in")
        lines.append("; the Zelda Oracle of Ages/Seasons disassembly) -- merge the m_waveform")
        lines.append("; blocks below into that file (in the m_waveform-referenced section, not")
        lines.append("; any orphaned/unused blocks), assign each a real free index, and bump")
        lines.append("; its waveform-count constant accordingly. The placeholder indices below")
        lines.append(f"; start at ${self.next_free_id_hint:02x} (the next free slot as of when this tool's")
        lines.append("; reference copy of that table was captured) -- verify against your")
        lines.append("; project's current table before merging, and renumber if it has moved on.")
        lines.append("; The channel-data files reference these waveforms by symbolic name (e.g.")
        lines.append("; `duty WF_SONGNAME_WAVE0_100`), so renumbering here is safe.")
        lines.append("")
        next_id = self.next_free_id_hint
        for entry in self.entries:
            users = sorted(entry['users'])
            lines.append("; Used by:")
            for song_name, wave_id, vol in users:
                lines.append(f";   {song_name}.s (source @wave{wave_id}, volume level {vol} = "
                              f"{VOL_LABEL[vol]}%)")
            lines.append(f"m_waveform ${next_id:02x}, {entry['name']}")
            byte_strs = ' '.join(f"${b:02x}" for b in entry['packed'])
            lines.append(f"\t.db {byte_strs}")
            lines.append("")
            next_id += 1
        return '\n'.join(lines) + '\n'
